{{- if .Values.kubeLoxilb.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-kube-loxilb
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-kube-loxilb
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
      - namespaces
      - services/status
    verbs:
      - get
      - watch
      - list
      - patch
      - update
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gatewayclasses/status
      - gateways
      - gateways/status
      - tcproutes
      - udproutes
    verbs: ["get", "watch", "list", "patch", "update"]
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - bgppeer.loxilb.io
    resources:
      - bgppeerservices
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - bgppolicydefinedsets.loxilb.io
    resources:
      - bgppolicydefinedsetsservices
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - bgppolicydefinition.loxilb.io
    resources:
      - bgppolicydefinitionservices
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - bgppolicyapply.loxilb.io
    resources:
      - bgppolicyapplyservices
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - loxiurl.loxilb.io
    resources:
      - loxiurls
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - egress.loxilb.io
    resources:
      - egresses
    verbs: ["get", "watch", "list", "patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-kube-loxilb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-kube-loxilb
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-kube-loxilb
    namespace: kube-system
---
apiVersion: apps/v1             
kind: Deployment           
metadata:                           
  name: {{ .Release.Name }}-kube-loxilb                        
  namespace: kube-system                           
  labels:                          
    app: {{ .Release.Name }}-kube-loxilb-app                           
spec:                             
  replicas: 1                             
  selector:                          
    matchLabels:                      
      app: {{ .Release.Name }}-kube-loxilb-app                            
  template:                         
    metadata:                          
      labels:                       
        app: {{ .Release.Name }}-kube-loxilb-app                    
    spec:                       
      dnsPolicy: ClusterFirstWithHostNet                         
      tolerations:                      
        # Mark the pod as a critical add-on for rescheduling.           
        - key: CriticalAddonsOnly            
          operator: Exists                          
      priorityClassName: system-node-critical                      
      serviceAccountName: {{ .Release.Name }}-kube-loxilb                       
      terminationGracePeriodSeconds: 0                    
      containers:                     
      - name: kube-loxilb                     
        image: "{{ .Values.kubeLoxilb.image.repository }}:{{ .Values.kubeLoxilb.image.tag }}"              
        imagePullPolicy: {{ .Values.kubeLoxilb.image.pullPolicy }}                      
        command:                   
        - /bin/kube-loxilb                
        args: {{ .Values.kubeLoxilb.args | toJson }}
        resources:
{{ toYaml .Values.kubeLoxilb.resources | indent 10 }}              
        securityContext:
{{ toYaml .Values.kubeLoxilb.securityContext | indent 10 }}
{{- end }} 