#
# Software Name : free5gc-helm
#
{{- with .Values.nef }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "free5gc-nef.fullname" $ }}-service
  labels:
    {{- include "free5gc-nef.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: 80
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-nef.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
{{- end }}
