apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: free5gc-nfs
  namespace: free5gc
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      project: free5gc
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http